### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by MicroWazzle** [Y0dax/azure-stt-subtitles-electron#7]
![image](https://user-images.githubusercontent.com/43018573/133919470-c0251e92-5c8d-4059-a76e-75cb85316825.png)
I did everything right I took the first key and put it in and did centralus and tried launching it but it didn't work. Sadge

**Comment by MicroWazzle** [comment]
The only thing I think it is is that a resource was require and the tutorial didnt say what to put in there.

**Comment by MicroWazzle** [comment]
New error https://i.imgur.com/J4tRLXX.png

**Comment by daronyondem** [comment]
I had the same issue running subtitles.html in the browser sandbox. The issue is primarily based on a Chrome update mentioned here https://stackoverflow.com/questions/55026293/google-chrome-javascript-issue-in-getting-user-audio-the-audiocontext-was-not. 

Here is how I worked around it.

First off, change the code here https://github.com/Y0dax/azure-stt-subtitles-electron/blob/master/js/subtitles.js#L37 modify the event listener to listen for simple `click` events. This will help us initiate the microphone listening by user interaction instead of automatically kicking it off, which is what is being blocked.

![image](https://user-images.githubusercontent.com/2984187/139576568-44f338c2-1a40-4a35-b71e-daa10ab8497d.png)

Next, we need to ensure OBS enables microphone access by default when a user on a website requests for it. This will prevent the microphone access pop up on the browser kick-in, which does not show up in the OBS browser source window at all. I suggest creating a shortcut to the OBS executable and configuring that to pass on the `--enable-media-stream` parameter.

![image](https://user-images.githubusercontent.com/2984187/139576769-77d5c0b2-18dd-43f6-9302-17558bbca760.png)

Now after launching OBS with the new shortcut, right-click on the browser source and select **Interact**.

![image](https://user-images.githubusercontent.com/2984187/139576633-616db6dd-a4e4-4ab4-85fd-f27cd979470d.png)

This will open a new window where you can interact with the browser content. In our case, it will look empty because there is nothing shown in the browser yet, and that is ok. Just click anywhere in the middle of the page and it should start the microphone listening. 

Hope this helps.

**Comment by Y0dax** [comment]
Thank you for the investigation and PR @daronyondem 

I am going to be taking a look at your changes in the next couple days to understand why it has this issue for you and @MicroWazzle. When I wrote this some time ago it was working well using OBS Studio 64 bit, without the need for activation via click, but something might have changed. I wish OBS had better ways for enabling webcam and microphone access.
